"""Add monthly_updates table and update widget_config

Revision ID: 4d7a9af42e47
Revises: 002_add_leads_table
Create Date: 2026-01-21 07:49:51.777471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d7a9af42e47'
down_revision: Union[str, Sequence[str], None] = '002_add_leads_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_updates',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('change_type', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('source_link', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_updates', schema=None) as batch_op:
        batch_op.create_index('idx_category_change_type', ['category', 'change_type'], unique=False)
        batch_op.create_index('idx_category_effective_date', ['category', 'effective_date'], unique=False)
        batch_op.create_index('idx_category_state', ['category', 'state'], unique=False)
        batch_op.create_index('idx_effective_date', ['effective_date'], unique=False)
        batch_op.create_index('idx_state_change_type', ['state', 'change_type'], unique=False)
        batch_op.create_index('idx_update_date', ['update_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_updates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_updates_change_type'), ['change_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_updates_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_updates_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_updates_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_updates_update_date'), ['update_date'], unique=False)

    with op.batch_alter_table('session_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_data_created_at'))
        batch_op.drop_index(batch_op.f('ix_session_data_is_active'))
        batch_op.drop_index(batch_op.f('ix_session_data_session_id'))

    op.drop_table('session_data')
    with op.batch_alter_table('widget_config', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('widget_config_tenant_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_widget_config_tenant_id'))
        batch_op.create_index(batch_op.f('ix_widget_config_tenant_id'), ['tenant_id'], unique=True)
        batch_op.create_index('idx_widget_secret_key', ['secret_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_widget_config_secret_key'), ['secret_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_widget_config_secret_key'))
        batch_op.drop_index('idx_widget_secret_key')
        batch_op.drop_index(batch_op.f('ix_widget_config_tenant_id'))
        batch_op.create_index(batch_op.f('ix_widget_config_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('widget_config_tenant_id_key'), ['tenant_id'], postgresql_nulls_not_distinct=False)

    op.create_table('session_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('user_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('chat_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('session_data_pkey')),
    sa.UniqueConstraint('session_id', name=op.f('session_data_session_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('session_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_data_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_data_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_data_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('monthly_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_updates_update_date'))
        batch_op.drop_index(batch_op.f('ix_monthly_updates_title'))
        batch_op.drop_index(batch_op.f('ix_monthly_updates_state'))
        batch_op.drop_index(batch_op.f('ix_monthly_updates_effective_date'))
        batch_op.drop_index(batch_op.f('ix_monthly_updates_change_type'))
        batch_op.drop_index(batch_op.f('ix_monthly_updates_category'))
        batch_op.drop_index('idx_update_date')
        batch_op.drop_index('idx_state_change_type')
        batch_op.drop_index('idx_effective_date')
        batch_op.drop_index('idx_category_state')
        batch_op.drop_index('idx_category_effective_date')
        batch_op.drop_index('idx_category_change_type')

    op.drop_table('monthly_updates')
    # ### end Alembic commands ###
