"""initial_migration_with_indices

Revision ID: ac63bc585842
Revises: 
Create Date: 2025-12-29 15:10:52.255727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac63bc585842'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('thread_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_threads', ['thread_id'], ['id'])
    op.drop_column('chat_messages', 'session_id')
    op.create_index(op.f('ix_chat_sessions_title'), 'chat_sessions', ['title'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_threads_session_id'), 'chat_threads', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_threads_title'), 'chat_threads', ['title'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_demos_customer_id'), 'demos', ['customer_id'], unique=False)
    op.create_index(op.f('ix_demos_status'), 'demos', ['status'], unique=False)
    op.create_index(op.f('ix_demos_title'), 'demos', ['title'], unique=False)
    op.create_index(op.f('ix_emails_customer_email'), 'emails', ['customer_email'], unique=False)
    op.create_index(op.f('ix_emails_subject'), 'emails', ['subject'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_emails_subject'), table_name='emails')
    op.drop_index(op.f('ix_emails_customer_email'), table_name='emails')
    op.drop_index(op.f('ix_demos_title'), table_name='demos')
    op.drop_index(op.f('ix_demos_status'), table_name='demos')
    op.drop_index(op.f('ix_demos_customer_id'), table_name='demos')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_chat_threads_title'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_session_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_title'), table_name='chat_sessions')
    op.add_column('chat_messages', sa.Column('session_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'thread_id')
    # ### end Alembic commands ###
