"""create_acts_table

Revision ID: e644a9a4dc16
Revises: ac63bc585842
Create Date: 2025-12-29 21:48:38.634672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e644a9a4dc16'
down_revision: Union[str, Sequence[str], None] = 'ac63bc585842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # with op.batch_alter_table('chat_messages', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'chat_threads', ['thread_id'], ['id'])
    #     batch_op.drop_column('session_id')

    # with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_chat_sessions_title'), ['title'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    # with op.batch_alter_table('chat_threads', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_chat_threads_session_id'), ['session_id'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_chat_threads_title'), ['title'], unique=False)

    # with op.batch_alter_table('customers', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)

    # with op.batch_alter_table('demos', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_demos_customer_id'), ['customer_id'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_demos_status'), ['status'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_demos_title'), ['title'], unique=False)

    # with op.batch_alter_table('emails', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_emails_customer_email'), ['customer_email'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_emails_subject'), ['subject'], unique=False)

    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)
    #     batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_name'))

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_subject'))
        batch_op.drop_index(batch_op.f('ix_emails_customer_email'))

    with op.batch_alter_table('demos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demos_title'))
        batch_op.drop_index(batch_op.f('ix_demos_status'))
        batch_op.drop_index(batch_op.f('ix_demos_customer_id'))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_name'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    with op.batch_alter_table('chat_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_threads_title'))
        batch_op.drop_index(batch_op.f('ix_chat_threads_session_id'))

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_title'))

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_sessions', ['session_id'], ['id'])

    # ### end Alembic commands ###
